spring:
  profiles:
    active: dev
  application:
    # \u670D\u52A1\u7AEF\u521B\u5EFA\u7684\u9879\u76EE id \u9700\u8981\u4E0E application.name \u4FDD\u6301\u4E00\u81F4
    name: dynamic-threadpool-example
  dynamic:
    thread-pool:
      # \u670D\u52A1\u7AEF\u5730\u5740
      server-addr: http://localhost:6691
      # \u7528\u6237\u540D
      username: admin
      # \u5BC6\u7801
      password: 123456
      # \u79DF\u6237 id, \u5BF9\u5E94 tenant \u8868
      namespace: prescription
      # \u9879\u76EE id, \u5BF9\u5E94 item \u8868
      item-id: ${spring.application.name}