spring:
  application:
    name: metricsLocalApp
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    \u5F00\u542Fdruid\u9A71\u52A8
    type: com.alibaba.druid.pool.DruidDataSource
#\u8C03\u5EA6\u914D\u7F6E
org:
  quartz:
    scheduler:
      #\u8C03\u5EA6\u5668\u5B9E\u4F8B\u540D\u79F0
      instanceName: MaterialFromEamScheduler
      #\u8C03\u5EA6\u5668\u5B9E\u4F8B\u7F16\u53F7\u81EA\u52A8\u751F\u6210
      instanceId: AUTO
      #\u662F\u5426\u5728Quartz\u6267\u884C\u4E00\u4E2Ajob\u524D\u4F7F\u7528UserTransaction
      wrapJobExecutionInUserTransaction: false
    #\u7EBF\u7A0B\u6C60\u914D\u7F6E
    threadPool:
      #\u7EBF\u7A0B\u6C60\u7684\u5B9E\u73B0\u7C7B
      class: org.quartz.simpl.SimpleThreadPool
      #\u7EBF\u7A0B\u6C60\u4E2D\u7684\u7EBF\u7A0B\u6570\u91CF
      threadCount: 10
      #\u7EBF\u7A0B\u4F18\u5148\u7EA7
      threadPriority: 5
      #\u914D\u7F6E\u662F\u5426\u542F\u52A8\u81EA\u52A8\u52A0\u8F7D\u6570\u636E\u5E93\u5185\u7684\u5B9A\u65F6\u4EFB\u52A1\uFF0C\u9ED8\u8BA4true
      threadsInheritContextClassLoaderOfInitializingThread: true
    #\u6301\u4E45\u5316\u65B9\u5F0F\u914D\u7F6E
    jobStore:
      #JobDataMaps\u662F\u5426\u90FD\u4E3AString\u7C7B\u578B
      useProperties: true
      #\u6570\u636E\u8868\u7684\u524D\u7F00\uFF0C\u9ED8\u8BA4QRTZ_
      tablePrefix: QRTZ_
      #\u6700\u5927\u80FD\u5FCD\u53D7\u7684\u89E6\u53D1\u8D85\u65F6\u65F6\u95F4
      misfireThreshold: 60000
      #\u662F\u5426\u4EE5\u96C6\u7FA4\u65B9\u5F0F\u8FD0\u884C
      isClustered: true
      #\u8C03\u5EA6\u5B9E\u4F8B\u5931\u6548\u7684\u68C0\u67E5\u65F6\u95F4\u95F4\u9694\uFF0C\u5355\u4F4D\u6BEB\u79D2
      clusterCheckinInterval: 2000
      maxMisfiresToHandleAtATime: 1
      #\u6570\u636E\u4FDD\u5B58\u65B9\u5F0F\u4E3A\u6570\u636E\u5E93\u6301\u4E45\u5316
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      #\u6570\u636E\u5E93\u4EE3\u7406\u7C7B\uFF0C\u4E00\u822Corg.quartz.impl.jdbcjobstore.StdJDBCDelegate\u53EF\u4EE5\u6EE1\u8DB3\u5927\u90E8\u5206\u6570\u636E\u5E93
      driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      # \u662F\u5426\u5F00\u542F\u60B2\u89C2\u9501\u63A7\u5236\u96C6\u7FA4\u4E2Dtrigger\u5E76\u53D1
      acquireTriggersWithinLock: true
      #\u6570\u636E\u5E93\u522B\u540D \u968F\u4FBF\u53D6
      dataSource: qzDS
      #\u6570\u636E\u5E93\u8FDE\u63A5\u6C60\uFF0C\u5C06\u5176\u8BBE\u7F6E\u4E3Adruid
    dataSource:
      qzDS:
        connectionProvider:
          class: com.example.yxy.config.DruidConnectionProvider
        #\u6570\u636E\u5E93\u5F15\u64CE
        driver: com.mysql.cj.jdbc.Driver
        #\u6570\u636E\u5E93\u8FDE\u63A5
        URL: jdbc:mysql://127.0.0.1:3306/quartz?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
        #\u6570\u636E\u5E93\u7528\u6237
        user: root
        #\u6570\u636E\u5E93\u5BC6\u7801
        password: 123456789
        #\u5141\u8BB8\u6700\u5927\u8FDE\u63A5
        maxConnection: 100