spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/r2dbc
    username: root
    password: 123456789
    pool:
      enabled: true
      max-size: 50
      min-idle: 10

server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  show-actuator: true